[tool.poetry]
name = "system-metrics-backend"
version = "0.1.0"
description = "Backend for System Metrics and Log Analytics Platform"
authors = ["Kiarash Bashokian <kiarash.bashokian2024@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
psutil = "^5.9.8"
sqlalchemy = "^2.0.29"
redis = "^5.0.4"
pydantic-settings = "^2.0.0"
psycopg2-binary = "^2.9.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
httpx = "^0.27.0" # HTTPX is a great async-capable client for testing FastAPI

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::PendingDeprecationWarning:starlette.formparsers",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
